# ***Title : -  purchase ddata model preprocesing ***

---



# **Basic step  involve  i envlove in data preprocessing **


 1 - import Library

 2 - Read dataset from outer Environment

3 - Identify what kind of data

4 - Handle with missing value ( sklearn impute function)

5 -  Encoding Categorical Data

6 - prepare and split data in training dataset and test dataset


6 - Faeture Scaling








In [1]:
import numpy as np
import pandas as pd

Read dataset from outer Environment : - download dataset in my github profile  which is form in csv file
copy path and paste it  as it is we shown in below .


In [2]:
Dataset = pd.read_csv("/content/Data.csv")

In [3]:
Dataset.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [4]:
x = Dataset[["Country","Age","Salary"]].values

In [5]:
y = Dataset[["Purchased"]].values

Handle missing value : -  we also use fill missing value using fillna function
But  here we use sklearn library function name SimpleImputer

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
imputer = SimpleImputer()

In [ ]:
imputer = SimpleImputer(missing_values = np.nan,strategy= 'mean')

In [ ]:
imputer = imputer.fit(x[:,1:3])

In [ ]:
x[:,1:3]= imputer.transform(x[:,1:3])

ENCODING CATEGORICAL DATA

 let suppose we transform country name into machine readble form before training  machine learninng model .


     When we tranform using preprocessing using labelencoder


     show this type of array [ 0,1,2,3,4,5-----etc ]
     but problem this sometimes macine learning model understand 0 is less then 1 and 1 is less then 2 who is absolutely wrong

  show in this stage after label encoding we use one another library which name is One hot encoder (dummy encoding )
  he shows value in form of   this
   
  
                                  array  ([[1., 0., 0.],
                                           [0., 0., 1.],
                                           [0., 1., 0.],
                                           [0., 0., 1.],
                                           [0., 1., 0.],
                                           [1., 0., 0.],
                                           [0., 0., 1.],
                                           [1., 0., 0.],
                                           [0., 1., 0.],
                                           [1., 0., 0.]])



In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
label_encder_x = LabelEncoder()

In [ ]:
x[:,0] = label_encder_x.fit_transform(x[:,0])

In [ ]:
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

After Encoding we find issue all value in 0,1,2---


suppse my train datset is assume 0<1<2


## Use Dummy Encoder

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe = OneHotEncoder()

In [ ]:
x= ohe.fit_transform(Dataset.Country.values.reshape(-1,1)).toarray()

In [ ]:
x

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [ ]:
y

array([['No'],
       ['Yes'],
       ['No'],
       ['No'],
       ['Yes'],
       ['Yes'],
       ['No'],
       ['Yes'],
       ['No'],
       ['Yes']], dtype=object)

In [ ]:
label_encoder_y = LabelEncoder()

In [ ]:
y = label_encoder_y.fit_transform(y)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [ ]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state = 0)

In [ ]:
x_train,y_train

(array([[-1.        ,  2.64575131, -0.77459667],
        [ 1.        , -0.37796447, -0.77459667],
        [-1.        , -0.37796447,  1.29099445],
        [-1.        , -0.37796447,  1.29099445],
        [ 1.        , -0.37796447, -0.77459667],
        [-1.        , -0.37796447,  1.29099445],
        [ 1.        , -0.37796447, -0.77459667],
        [ 1.        , -0.37796447, -0.77459667]]),
 array([1, 1, 1, 0, 1, 0, 0, 1]))

In [ ]:
x_test

array([[0., 1., 0.],
       [0., 1., 0.]])

Feature Scaling  ; -  Highly very  same scaleing  


sometimes we see some data are varying out scaling

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
st = StandardScaler()

In [ ]:
x_train= st.fit_transform(x_train)

In [ ]:
x_train

array([[-1.        ,  2.64575131, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [-1.        , -0.37796447,  1.29099445],
       [ 1.        , -0.37796447, -0.77459667],
       [ 1.        , -0.37796447, -0.77459667]])

In [ ]:
x_test = st.fit_transform(x_test)

In [ ]:
x_test

array([[0., 0., 0.],
       [0., 0., 0.]])